- name: Run Terraform script from GitHub
  hosts: localhost
  tasks:
    - name: Log in to Azure CLI using Tower credential
      ansible.builtin.azure_login:
        client_id: "{{ lookup('tower_credential', 'AZURE_CLIENT_ID', 'abhitets') }}"
        secret: "{{ lookup('tower_credential', 'AZURE_SECRET', 'abhitets') }}"
        tenant: "{{ lookup('tower_credential', 'AZURE_TENANT', 'abhitets') }}"
      register: login_output
    - name: Clone the Terraform script repository
      git:
        repo: 'https://github.com/Abhi90270102/scripttf.git'
        dest: /tmp/terraform-scripts

    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: /tmp/terraform-scripts

    - name: Plan Terraform
      command: terraform plan
      args:
        chdir: /tmp/terraform-scripts    

    - name: Apply Terraform configuration
      command: terraform apply -auto-approve
      args:
        chdir: /tmp/terraform-scripts
